### PR TITLE
Fix HTML error rendering, skip header lines on PowerSchool schedules

### PR DESCRIPTION
**Pull request by devksingh4**
When PowerSchool schedules are currently pasted in with their headers, the tool fails as the headers are not processable. This PR filters out all lines that do not start with numbers so that these headers do not cause errors. 

This PR also fixes error reporting on the PowerSchool ingest box.

### CODE REVIEW

**Comment by geosir** [comment]
Hi @devksingh4, apologies for the super delayed response, I just saw this! Your PR checks out and it's ready to merge - although, if possible, could you show me a sample schedule paste before I close this out? I'd like to see if the format has changed since last time. Thanks for submitting updates, it's really has been a while (this was made before `URLSearchParams`??)

**Comment by devksingh4** [comment]
Hi @geosir, 
Here is a PowerSchool paste:
<html>
<body>


Y21-22 Semester 2
--
Exp | Trm | Crs-Sec | Course Name | Teacher | Room | Enroll | Leave
1(A-B,D,Sp) | S2 | ENG351-1 | Graphic Novels: Image and Text | Dean, Michael P | A114 | 01/10/2022 | 06/12/2022
2(A-D) 5(Sp) | S2 | MAT445-1 | Theory of Analysis | Fogel, Micah | A156 | 01/09/2022 | 06/12/2022
4(A,C-D) 6(Sp) | S2 | HSS394-1 | Modern Conflict, Insurgency & Terrorism | Eysturlid, Lee | MathStudy | 01/09/2022 | 06/12/2022
MD1(A-I) | S2 | LUN100-102 | Lunch | Staff, Cafeteria | Cafeteria | 01/18/2022 | 06/12/2022
MD3(A,D) | Y21-22 | SLD150-43 | Titan Crew | Schmidt, Brooke | B116 | 08/23/2021 | 06/16/2022
RC(A-Sp) | Y21-22 | SLD130-7 | Rolling Check | Staff, Residential Life | C130 | 08/21/2021 | 06/15/2022
CC(A-Sp) | Y21-22 | SLD120-7 | Curfew Check | Staff, Residential Life | C130 | 08/21/2021 | 06/15/2022
6(I) | Y21-22 | SIR200-101 | Student Inquiry and Research | Staff, SIR | B131 | 08/25/2021 | 06/15/2022
AS(I) | Y21-22 | SLD100-8 | Residential Life | Gehrke, Alyssa | 1507A | 08/25/2021 | 06/15/2022
2(Sp) 3(A-D) | S2 | CS431-1 | CS Seminar: Machine Learning | Patankar, Phadmakar A | A133 | 01/10/2022 | 06/12/2022
5(A-D) 3(Sp) | S2 | WLG250-201 | Spanish V | Kaluza, Marta J | A135 | 01/09/2022 | 06/12/2022
7-8(B,D) 4(Sp) | S2 | SCI412-2 | Physics: Calculus-based Elec & Magnetism | Schmidt, Brooke | B133 | 01/09/2022 | 06/12/2022


</body>
</html>

Here is the resulting render:
image

I also modified the license and copyright to reflect my changes and fixed a small grammar error (4rd vs. 4th).

**Comment by devksingh4** [comment]
Also, I believe `URLSearchParams` has been available since 2016 or 2017 but probably wasn't supported on more niche browsers.

**Comment by geosir** [comment]
Appreciate the paste! Just to confirm, does each ` | ` above represent a tab character in the actual input?

Also, thanks for pointing out that the license should be updated to support contributions. I've revised [LICENSE](LICENSE) and [the copyright line](https://github.com/geosir/imsa-scheduler/blob/210a8e57add502e67fa51ca5d78dda855b5419ee/index.html#L289) to reflect convention used by other open-source projects. I've also linked [contributors.html](contributors.html) to that new copyright line so that contributors have a place to put their credits there if they want.

Please go ahead and add yourself to contributors.html and resolve conflicts to fit the new format.

**Comment by devksingh4** [comment]
Yes the `|` represents a tab - I don't know why GitHub decided to transform it into pipes. I have updated my branch to fit the new format.

**Pull request merged**
